name: Defender DevOps Scan (MSDO)

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write             # Required for Microsoft identity federation
  security-events: write      # Required for SARIF upload to GitHub Security tab


jobs:
  defender-devops:
    name: Run Defender DevOps Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@v1
        id: msdo
      - name: Debug Token Scope
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" https://api.github.com/user

      - name: Upload results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
          token: ${{ secrets.GITHUB_TOKEN}}

      - name: Upload SARIF as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: alerts
          path: ${{ steps.msdo.outputs.sarifFile }}


      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
          token: ${{ secrets.GITHUB_TOKEN }}  # 🔐 Uses the PAT secret

