# name: Defender DevOps Scan (MSDO)

# on:
#   push:
#     branches: [main]

# permissions:
#   contents: read
#   id-token: write             # Required for Microsoft identity federation
#   security-events: write      # Required for SARIF upload to GitHub Security tab

# env:
#   imageTag: test-app:latest

# jobs:
#   defender-devops:
#     name: Run Defender DevOps Scans
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v4

#       - name: Build Docker image for test-app
#         run: |
#           docker build -t ${{ env.imageTag }} .

#       - name: Run Microsoft Security DevOps Analysis (Generic)
#         id: general-scan
#         uses: microsoft/security-devops-action@latest

#       - name: Setup .NET 6 runtime for CredScan
#         uses: actions/setup-dotnet@v4
#         with:
#           dotnet-version: '6.0.x'

#       - name: Run Secret Scan using Microsoft Security DevOps
#         id: secretscan
#         uses: microsoft/security-devops-action@latest
#         with:
#           policy: microsoft
#           categories: secrets
#           tools: credscan

#       - name: Upload Secret Scan results to GitHub Security tab
#         uses: github/codeql-action/upload-sarif@v3
#         with:
#           sarif_file: ${{ steps.secretscan.outputs.sarifFile }}
#           token: ${{ secrets.GITHUB_TOKEN }}
#           category: secrets-scan   

#       # - name: Run Microsoft Security DevOps Analysis
#       #   id: msdo
#       #   uses: microsoft/security-devops-action@latest
#       #   with:
#       #     policy: microsoft
#       #     categories: containers
#       #     tools: trivy
#       #   env:
#       #     GDN_TRIVY_ACTION: "image"
#       #     GDN_TRIVY_TARGET: "${{ env.imageTag }}"
#       #     GDN_TRIVY_IGNOREUNFIXED: true
#       #     GDN_TRIVY_SEVERITIES: "HIGH,CRITICAL"



#       # - name: Upload results to GitHub Security tab
#       #   uses: github/codeql-action/upload-sarif@v3
#       #   with:
#       #     sarif_file: ${{ steps.msdo.outputs.sarifFile }}
#       #     token: ${{ secrets.GITHUB_TOKEN }}
#       #     category: container-scan 

#       # - name: Upload SARIF as build artifact
#       #   uses: actions/upload-artifact@v4
#       #   with:
#       #     name: alerts
#       #     path: ${{ steps.msdo.outputs.sarifFile }}

jobs:
  # JOB 1 — Secrets Scan (CredScan)
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Run Secret Scan using Microsoft Security DevOps
        id: secretscan
        uses: microsoft/security-devops-action@latest
        with:
          policy: microsoft
          categories: secrets
          tools: credscan
      - name: Upload Secret Scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.secretscan.outputs.sarifFile }}
          token: ${{ secrets.GITHUB_TOKEN }}
          category: secrets-scan

  # JOB 2 — Container Scan (Trivy)
  container-scan:
    runs-on: ubuntu-latest
    needs: secret-scan
    env:
      imageTag: test-app:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build test app container image
        run: docker build -t ${{ env.imageTag }} .

      - name: Run Microsoft Security DevOps Analysis (Trivy)
        id: msdo
        uses: microsoft/security-devops-action@latest
        with:
          policy: microsoft
          categories: containers
          tools: trivy
        env:
          GDN_TRIVY_ACTION: "image"
          GDN_TRIVY_TARGET: "${{ env.imageTag }}"
          GDN_TRIVY_IGNOREUNFIXED: true
          GDN_TRIVY_SEVERITIES: "HIGH,CRITICAL"

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
          token: ${{ secrets.GITHUB_TOKEN }}
          category: container-scan

